function lastMaskInitialState(app)
    app.lastMask_text.Enable = 0;
    app.lastMask_text.Text   = {'<b style="color: #a2142f; font-size: 14;">-1</b> ';                ...
                                'VALIDAÇÕES '; '<b style="color: #a2142f; font-size: 14;">-1</b> '; ...
                                'ROMPIMENTOS '; '<font style="color: #a2142f;">-1.000 MHz ';        ...
                                '⌂ -1.0 kHz ';                                                      ...
                                'Ʌ -1.0 dB </font>';                                                ...
                                'dd-mmm-yyyy ';                                                     ...
                                'HH:MM:SS '};
end