classdef ExtensionInfo < handle
    %ExtensionInfo Defines a class used to tell an AppContainer about custom JavaScript
    % and CSS assocated with children implemented in JavaScript rather than as figures.

    % Copyright 2019-2021 The MathWorks, Inc.

    properties
        % <matlab root> relative path to a config file that identifies the locations where
        % individual JavaScript files can be found.  The individual files are used only
        % when debugging.  Otherwise the ReleasePackageNames, ReleasePackageLocations &
        % ReleaseMainFileNames are used (see below).
        DebugConfigFile (1,1) string = "";
        
        % <matlab root> relative path to a file containing CSS to be loaded when debugging
        DebugCSSFile (1,1) string = "";
        
        % <matlab root> String array of relative paths to the CSS files generated by the
        % release build process. (AppContainer debugPort ~= 0).
        ReleaseCSSFiles (:,:) string = ""; 
        
        % String array of component names used to identify the components in the build system.
        % Each array index is mapped to a corresponding array index in ReleasePackageLocations &
        % ReleaseMainFileName. (AppContainer debugPort ~= 0).
        ReleasePackageNames (:,:) string = "";
        
        % <matlab root> String array of relative paths to directories containing JavaScript
        % code packaged for release.  Each array index is mapped to a corresponding array
        % index in ReleasePackageNames & ReleaseMainFileName. (AppContainer debugPort ~= 0).
        ReleasePackageLocations (:,:) string = "";
        
        % String array of filenames for the minified code files generated by the build system.
        % Each array index is mapped to a corresponding array index in ReleasePackageNames &
        % ReleasePackageLocations. (AppContainer debugPort ~= 0).
        ReleaseMainFileNames (:,:) string = "";
        
        % ModuleInfo array of modules to be loaded.
        Modules (:,:) matlab.ui.container.internal.appcontainer.ModuleInfo;
    end
end

